version: '3'
services:
  webserver:
    build:
      context: ./webserver
      dockerfile: server.Dockerfile
    volumes: 
      - ./webserver/src:/myapp    
  reverseproxy:
    environment:
      - DOMAIN_NAME= example.com
      - EMAIL= example@example.com    
      - PROXY_PASS_HOST=webserver 
      - PROXY_PASS_PORT=8000  
      - PROXY_PASS_PROTOCOL=http
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    volumes:
     # - ./nginx/cert:/etc/letsencrypt/live
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    ports:
       - 443:443
       - 80:80
    links: 
      - webserver